#storage:
#  engine: mmapv1
#  engine: wiredTiger
#  engine: PerconaFT
#  PerconaFT:
#    collectionOptions:
#      fanout: 32

#storage:
#  engine: rocksdb
#  rocksdb:
#    configString: "skip_stats_update_on_db_open=true"

#operationProfiling:
#  rateLimit: 17

#security:
#  authenticationMechanisms:
#    - SCRAM-SHA-1
#    - PLAIN

storage:
  dbPath: /home/igor/repo/data/wt-zstd
  engine: wiredTiger
  wiredTiger:
    collectionConfig:
      blockCompressor: zstd

